name: 📦 Archive Gradle reports
description: Archive Gradle reports

inputs:
  id:
    description: A unique identifier, to avoid collisions when using matrix strategy
    required: false

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v6
      with:
        # Format unique identifiers:
        # - gradle-reports-[job]
        # - gradle-reports-[job#id]
        name: ${{ format(format('gradle-reports-[{0}]', case(inputs.id == '', '{0}', '{0}#{1}')), github.job, inputs.id) }}
        path: |
          build/reports/configuration-cache/**/*.html
          build/reports/dependency-configuration-cache
          build/reports/dependency-verification
          build/reports/problems/problems-report.html
        if-no-files-found: ignore
